CREATE OR REPLACE TABLE RELATIONSHIP_DISCOVERY_DB.SRC.ERP_PRODUCT (
    ERP_PRODUCT_ID NUMBER AUTOINCREMENT,
    PRODUCT_CODE VARCHAR(50) NOT NULL,
    BRAND_NAME VARCHAR(200),
    PRODUCT_DESCRIPTION VARCHAR(500),
    PRODUCT_CATEGORY VARCHAR(200),
    MANUFACTURER_NAME VARCHAR(200),
    LIST_PRICE NUMBER(12,2),
    PRODUCT_SIZE VARCHAR(100),
    LOAD_DTTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RELATIONSHIP_DISCOVERY_DB.SRC.SUPPLIER_PRODUCT (
    SUPPLIER_PRODUCT_ID NUMBER AUTOINCREMENT,
    ITEM_CODE VARCHAR(50) NOT NULL,
    ITEM_NAME VARCHAR(500),
    BRAND VARCHAR(200),
    CATEGORY_DESCRIPTION VARCHAR(200),
    MFG_NAME VARCHAR(200),
    UNIT_COST NUMBER(12,2),
    PACK_SIZE VARCHAR(100),
    LOAD_DTTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RELATIONSHIP_DISCOVERY_DB.SRC.INVENTORY_PRODUCT (
    INVENTORY_PRODUCT_ID NUMBER AUTOINCREMENT,
    SKU_CODE VARCHAR(50) NOT NULL,
    SKU_DESCRIPTION VARCHAR(500),
    BRAND_CODE VARCHAR(200),
    STORAGE_CATEGORY VARCHAR(200),
    REORDER_COST NUMBER(12,2),
    WEIGHT_SIZE VARCHAR(100),
    LOAD_DTTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RELATIONSHIP_DISCOVERY_DB.SRC.ECOMMERCE_PRODUCT (
    ECOMMERCE_PRODUCT_ID NUMBER AUTOINCREMENT,
    VENDOR_CODE VARCHAR(50) NOT NULL,
    LISTING_TITLE VARCHAR(500),
    VENDOR_NAME VARCHAR(200),
    WEB_CATEGORY VARCHAR(200),
    SELLER_NAME VARCHAR(200),
    SELLING_PRICE NUMBER(12,2),
    DISPLAY_SIZE VARCHAR(100),
    LOAD_DTTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
