/*======================================================================
  017_SECURITY_IMPLEMENTATION.SQL
  Platform Security – RBAC and Dynamic Data Masking.

  Implements:
    - 4 application roles (least privilege)
    - Future grants for schema growth
    - 3 masking policies (role-aware)
    - Policy application to FINAL + INTM tables

  Does not implement:
    - Row Access Policies
    - ABAC / OAuth / SSO / MFA
======================================================================*/

----------------------------------------------------------------------
-- PHASE 1: Create Application Roles
----------------------------------------------------------------------
USE ROLE SYSADMIN;

CREATE ROLE IF NOT EXISTS MDM_ADMIN
  COMMENT = 'Full MDM platform access including security administration';

CREATE ROLE IF NOT EXISTS MDM_DATA_STEWARD
  COMMENT = 'Read access to metadata, master data, action log and audit history';

CREATE ROLE IF NOT EXISTS MDM_BUSINESS_USER
  COMMENT = 'Read access to FINAL.PRODUCT_MASTER only';

CREATE ROLE IF NOT EXISTS MDM_AUDITOR
  COMMENT = 'Read access to action log, version history and metadata';

----------------------------------------------------------------------
-- PHASE 2: Grants (independent roles, no hierarchy)
-- No grants to SYSADMIN/ACCOUNTADMIN/SECURITYADMIN
----------------------------------------------------------------------

----------------------------------------------------------------------
-- PHASE 3: MDM_ADMIN Grants – Full Database Access
----------------------------------------------------------------------
GRANT USAGE ON DATABASE RELATIONSHIP_DISCOVERY_DB TO ROLE MDM_ADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RELATIONSHIP_DISCOVERY_DB TO ROLE MDM_ADMIN;
GRANT SELECT ON ALL TABLES IN DATABASE RELATIONSHIP_DISCOVERY_DB TO ROLE MDM_ADMIN;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE RELATIONSHIP_DISCOVERY_DB TO ROLE MDM_ADMIN;
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE RELATIONSHIP_DISCOVERY_DB TO ROLE MDM_ADMIN;
GRANT USAGE ON WAREHOUSE EXERCISE_WAREHOUSE TO ROLE MDM_ADMIN;

GRANT SELECT ON FUTURE TABLES IN SCHEMA RELATIONSHIP_DISCOVERY_DB.LOG TO ROLE MDM_ADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RELATIONSHIP_DISCOVERY_DB.INTM TO ROLE MDM_ADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RELATIONSHIP_DISCOVERY_DB.FINAL TO ROLE MDM_ADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RELATIONSHIP_DISCOVERY_DB.MD TO ROLE MDM_ADMIN;

----------------------------------------------------------------------
-- PHASE 4: MDM_DATA_STEWARD Grants – Read Metadata + Master + Log
----------------------------------------------------------------------
GRANT USAGE ON DATABASE RELATIONSHIP_DISCOVERY_DB TO ROLE MDM_DATA_STEWARD;
GRANT USAGE ON SCHEMA RELATIONSHIP_DISCOVERY_DB.FINAL TO ROLE MDM_DATA_STEWARD;
GRANT USAGE ON SCHEMA RELATIONSHIP_DISCOVERY_DB.INTM TO ROLE MDM_DATA_STEWARD;
GRANT USAGE ON SCHEMA RELATIONSHIP_DISCOVERY_DB.LOG TO ROLE MDM_DATA_STEWARD;
GRANT USAGE ON SCHEMA RELATIONSHIP_DISCOVERY_DB.MD TO ROLE MDM_DATA_STEWARD;

GRANT SELECT ON ALL TABLES IN SCHEMA RELATIONSHIP_DISCOVERY_DB.FINAL TO ROLE MDM_DATA_STEWARD;
GRANT SELECT ON ALL TABLES IN SCHEMA RELATIONSHIP_DISCOVERY_DB.INTM TO ROLE MDM_DATA_STEWARD;
GRANT SELECT ON ALL TABLES IN SCHEMA RELATIONSHIP_DISCOVERY_DB.LOG TO ROLE MDM_DATA_STEWARD;
GRANT SELECT ON ALL TABLES IN SCHEMA RELATIONSHIP_DISCOVERY_DB.MD TO ROLE MDM_DATA_STEWARD;

GRANT SELECT ON FUTURE TABLES IN SCHEMA RELATIONSHIP_DISCOVERY_DB.FINAL TO ROLE MDM_DATA_STEWARD;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RELATIONSHIP_DISCOVERY_DB.INTM TO ROLE MDM_DATA_STEWARD;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RELATIONSHIP_DISCOVERY_DB.LOG TO ROLE MDM_DATA_STEWARD;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RELATIONSHIP_DISCOVERY_DB.MD TO ROLE MDM_DATA_STEWARD;

GRANT USAGE ON WAREHOUSE EXERCISE_WAREHOUSE TO ROLE MDM_DATA_STEWARD;

----------------------------------------------------------------------
-- PHASE 5: MDM_BUSINESS_USER Grants – FINAL Only
----------------------------------------------------------------------
GRANT USAGE ON DATABASE RELATIONSHIP_DISCOVERY_DB TO ROLE MDM_BUSINESS_USER;
GRANT USAGE ON SCHEMA RELATIONSHIP_DISCOVERY_DB.FINAL TO ROLE MDM_BUSINESS_USER;

GRANT SELECT ON ALL TABLES IN SCHEMA RELATIONSHIP_DISCOVERY_DB.FINAL TO ROLE MDM_BUSINESS_USER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RELATIONSHIP_DISCOVERY_DB.FINAL TO ROLE MDM_BUSINESS_USER;

GRANT USAGE ON WAREHOUSE EXERCISE_WAREHOUSE TO ROLE MDM_BUSINESS_USER;

----------------------------------------------------------------------
-- PHASE 6: MDM_AUDITOR Grants – Log + Version History + Metadata
----------------------------------------------------------------------
GRANT USAGE ON DATABASE RELATIONSHIP_DISCOVERY_DB TO ROLE MDM_AUDITOR;
GRANT USAGE ON SCHEMA RELATIONSHIP_DISCOVERY_DB.LOG TO ROLE MDM_AUDITOR;
GRANT USAGE ON SCHEMA RELATIONSHIP_DISCOVERY_DB.INTM TO ROLE MDM_AUDITOR;
GRANT USAGE ON SCHEMA RELATIONSHIP_DISCOVERY_DB.MD TO ROLE MDM_AUDITOR;

GRANT SELECT ON ALL TABLES IN SCHEMA RELATIONSHIP_DISCOVERY_DB.LOG TO ROLE MDM_AUDITOR;
GRANT SELECT ON ALL TABLES IN SCHEMA RELATIONSHIP_DISCOVERY_DB.INTM TO ROLE MDM_AUDITOR;
GRANT SELECT ON ALL TABLES IN SCHEMA RELATIONSHIP_DISCOVERY_DB.MD TO ROLE MDM_AUDITOR;

GRANT SELECT ON FUTURE TABLES IN SCHEMA RELATIONSHIP_DISCOVERY_DB.LOG TO ROLE MDM_AUDITOR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RELATIONSHIP_DISCOVERY_DB.INTM TO ROLE MDM_AUDITOR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RELATIONSHIP_DISCOVERY_DB.MD TO ROLE MDM_AUDITOR;

GRANT USAGE ON WAREHOUSE EXERCISE_WAREHOUSE TO ROLE MDM_AUDITOR;

----------------------------------------------------------------------
-- PHASE 7: Dynamic Masking Policy – SALE_PRICE
-- Visible: MDM_ADMIN, MDM_DATA_STEWARD
-- Masked:  MDM_BUSINESS_USER, MDM_AUDITOR
----------------------------------------------------------------------
USE ROLE SYSADMIN;

CREATE OR REPLACE MASKING POLICY RELATIONSHIP_DISCOVERY_DB.FINAL.MASK_SALE_PRICE
  AS (val NUMBER(18,2))
  RETURNS NUMBER(18,2) ->
  CASE
    WHEN CURRENT_ROLE() IN ('MDM_ADMIN', 'MDM_DATA_STEWARD') THEN val
    ELSE NULL
  END;

----------------------------------------------------------------------
-- PHASE 8: Dynamic Masking Policy – SOURCE_EXECUTION_REFERENCE
-- Visible: MDM_ADMIN, MDM_DATA_STEWARD
-- Masked:  MDM_BUSINESS_USER, MDM_AUDITOR
----------------------------------------------------------------------
CREATE OR REPLACE MASKING POLICY RELATIONSHIP_DISCOVERY_DB.FINAL.MASK_SOURCE_EXECUTION_REFERENCE
  AS (val VARCHAR)
  RETURNS VARCHAR ->
  CASE
    WHEN CURRENT_ROLE() IN ('MDM_ADMIN', 'MDM_DATA_STEWARD') THEN val
    ELSE '***MASKED***'
  END;

----------------------------------------------------------------------
-- PHASE 9: Dynamic Masking Policy – ACTION_SOURCE
-- Visible: MDM_ADMIN, MDM_DATA_STEWARD, MDM_AUDITOR
-- Masked:  MDM_BUSINESS_USER
----------------------------------------------------------------------
CREATE OR REPLACE MASKING POLICY RELATIONSHIP_DISCOVERY_DB.FINAL.MASK_ACTION_SOURCE
  AS (val VARCHAR)
  RETURNS VARCHAR ->
  CASE
    WHEN CURRENT_ROLE() IN ('MDM_ADMIN', 'MDM_DATA_STEWARD', 'MDM_AUDITOR') THEN val
    ELSE '***MASKED***'
  END;

----------------------------------------------------------------------
-- PHASE 10: Apply Masking Policies – FINAL.PRODUCT_MASTER
----------------------------------------------------------------------
ALTER TABLE RELATIONSHIP_DISCOVERY_DB.FINAL.PRODUCT_MASTER
  MODIFY COLUMN SALE_PRICE
  SET MASKING POLICY RELATIONSHIP_DISCOVERY_DB.FINAL.MASK_SALE_PRICE;

ALTER TABLE RELATIONSHIP_DISCOVERY_DB.FINAL.PRODUCT_MASTER
  MODIFY COLUMN SOURCE_EXECUTION_REFERENCE
  SET MASKING POLICY RELATIONSHIP_DISCOVERY_DB.FINAL.MASK_SOURCE_EXECUTION_REFERENCE;

ALTER TABLE RELATIONSHIP_DISCOVERY_DB.FINAL.PRODUCT_MASTER
  MODIFY COLUMN ACTION_SOURCE
  SET MASKING POLICY RELATIONSHIP_DISCOVERY_DB.FINAL.MASK_ACTION_SOURCE;

----------------------------------------------------------------------
-- PHASE 11: Apply Masking Policies – INTM.INTM_PRODUCT_MASTER
----------------------------------------------------------------------
ALTER TABLE RELATIONSHIP_DISCOVERY_DB.INTM.INTM_PRODUCT_MASTER
  MODIFY COLUMN SALE_PRICE
  SET MASKING POLICY RELATIONSHIP_DISCOVERY_DB.FINAL.MASK_SALE_PRICE;

ALTER TABLE RELATIONSHIP_DISCOVERY_DB.INTM.INTM_PRODUCT_MASTER
  MODIFY COLUMN SOURCE_EXECUTION_REFERENCE
  SET MASKING POLICY RELATIONSHIP_DISCOVERY_DB.FINAL.MASK_SOURCE_EXECUTION_REFERENCE;

ALTER TABLE RELATIONSHIP_DISCOVERY_DB.INTM.INTM_PRODUCT_MASTER
  MODIFY COLUMN ACTION_SOURCE
  SET MASKING POLICY RELATIONSHIP_DISCOVERY_DB.FINAL.MASK_ACTION_SOURCE;

----------------------------------------------------------------------
-- VALIDATION 1: Masking Policy Assignments (per policy)
----------------------------------------------------------------------
SELECT POLICY_NAME, REF_DATABASE_NAME, REF_SCHEMA_NAME, REF_ENTITY_NAME, REF_COLUMN_NAME
FROM TABLE(RELATIONSHIP_DISCOVERY_DB.INFORMATION_SCHEMA.POLICY_REFERENCES(
  POLICY_NAME => 'MASK_SALE_PRICE'
));

SELECT POLICY_NAME, REF_DATABASE_NAME, REF_SCHEMA_NAME, REF_ENTITY_NAME, REF_COLUMN_NAME
FROM TABLE(RELATIONSHIP_DISCOVERY_DB.INFORMATION_SCHEMA.POLICY_REFERENCES(
  POLICY_NAME => 'MASK_SOURCE_EXECUTION_REFERENCE'
));

SELECT POLICY_NAME, REF_DATABASE_NAME, REF_SCHEMA_NAME, REF_ENTITY_NAME, REF_COLUMN_NAME
FROM TABLE(RELATIONSHIP_DISCOVERY_DB.INFORMATION_SCHEMA.POLICY_REFERENCES(
  POLICY_NAME => 'MASK_ACTION_SOURCE'
));

----------------------------------------------------------------------
-- VALIDATION 2: Role Grants
----------------------------------------------------------------------
SHOW GRANTS TO ROLE MDM_ADMIN;
SHOW GRANTS TO ROLE MDM_DATA_STEWARD;
SHOW GRANTS TO ROLE MDM_BUSINESS_USER;
SHOW GRANTS TO ROLE MDM_AUDITOR;

----------------------------------------------------------------------
-- VALIDATION 3: Security Coverage Summary
----------------------------------------------------------------------
SELECT
    'SALE_PRICE' AS PROTECTED_ATTRIBUTE,
    'MASK_SALE_PRICE' AS POLICY_NAME,
    'MDM_ADMIN, MDM_DATA_STEWARD' AS VISIBLE_TO,
    'MDM_BUSINESS_USER, MDM_AUDITOR' AS MASKED_FOR
UNION ALL
SELECT
    'SOURCE_EXECUTION_REFERENCE',
    'MASK_SOURCE_EXECUTION_REFERENCE',
    'MDM_ADMIN, MDM_DATA_STEWARD',
    'MDM_BUSINESS_USER, MDM_AUDITOR'
UNION ALL
SELECT
    'ACTION_SOURCE',
    'MASK_ACTION_SOURCE',
    'MDM_ADMIN, MDM_DATA_STEWARD, MDM_AUDITOR',
    'MDM_BUSINESS_USER';
