CREATE TABLE IF NOT EXISTS RELATIONSHIP_DISCOVERY_DB.MD.MD_ATTRIBUTE_DQ_RULES (
    DQ_RULE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    ATTRIBUTE_NAME VARCHAR(100) NOT NULL,
    IS_CRITICAL VARCHAR(1) NOT NULL,
    NULL_ALLOWED VARCHAR(1) NOT NULL,
    DQ_RULE_TYPE VARCHAR(50),
    DQ_RULE_DESCRIPTION VARCHAR(500),
    ACTIVE_FLAG VARCHAR(1) DEFAULT 'Y',
    CREATED_DTTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RELATIONSHIP_DISCOVERY_DB.MD.MD_ATTRIBUTE_SURVIVORSHIP (
    SURVIVORSHIP_RULE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    ATTRIBUTE_NAME VARCHAR(100) NOT NULL,
    SOURCE_SYSTEM VARCHAR(100) NOT NULL,
    PRIORITY_ORDER NUMBER NOT NULL,
    ACTIVE_FLAG VARCHAR(1) DEFAULT 'Y',
    CREATED_DTTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RELATIONSHIP_DISCOVERY_DB.MD.MD_ATTRIBUTE_MAPPING (
    MAPPING_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    CANONICAL_ATTRIBUTE VARCHAR(100) NOT NULL,
    SOURCE_SYSTEM VARCHAR(100) NOT NULL,
    SOURCE_ATTRIBUTE VARCHAR(100) NOT NULL,
    ACTIVE_FLAG VARCHAR(1) DEFAULT 'Y',
    CREATED_DTTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO RELATIONSHIP_DISCOVERY_DB.MD.MD_ATTRIBUTE_DQ_RULES (ATTRIBUTE_NAME, IS_CRITICAL, NULL_ALLOWED, DQ_RULE_TYPE, DQ_RULE_DESCRIPTION)
VALUES
    ('BRAND', 'Y', 'N', 'NOT_NULL', 'Brand must not be null'),
    ('PRODUCT_NAME', 'Y', 'N', 'NOT_NULL', 'Product name must not be null'),
    ('SIZE', 'Y', 'N', 'NOT_NULL', 'Size must not be null'),
    ('CATEGORY', 'N', 'Y', NULL, NULL),
    ('MANUFACTURER', 'N', 'Y', NULL, NULL),
    ('SALE_PRICE', 'N', 'Y', NULL, NULL);

INSERT INTO RELATIONSHIP_DISCOVERY_DB.MD.MD_ATTRIBUTE_SURVIVORSHIP (ATTRIBUTE_NAME, SOURCE_SYSTEM, PRIORITY_ORDER)
VALUES
    ('BRAND', 'ERP_PRODUCT', 1),
    ('BRAND', 'SUPPLIER_PRODUCT', 2),
    ('BRAND', 'ECOMMERCE_PRODUCT', 3),
    ('BRAND', 'INVENTORY_PRODUCT', 4),
    ('PRODUCT_NAME', 'ERP_PRODUCT', 1),
    ('PRODUCT_NAME', 'SUPPLIER_PRODUCT', 2),
    ('PRODUCT_NAME', 'ECOMMERCE_PRODUCT', 3),
    ('PRODUCT_NAME', 'INVENTORY_PRODUCT', 4),
    ('CATEGORY', 'ERP_PRODUCT', 1),
    ('CATEGORY', 'SUPPLIER_PRODUCT', 2),
    ('CATEGORY', 'ECOMMERCE_PRODUCT', 3),
    ('CATEGORY', 'INVENTORY_PRODUCT', 4),
    ('MANUFACTURER', 'ERP_PRODUCT', 1),
    ('MANUFACTURER', 'SUPPLIER_PRODUCT', 2),
    ('MANUFACTURER', 'ECOMMERCE_PRODUCT', 3),
    ('MANUFACTURER', 'INVENTORY_PRODUCT', 4),
    ('SALE_PRICE', 'ERP_PRODUCT', 1),
    ('SALE_PRICE', 'SUPPLIER_PRODUCT', 2),
    ('SALE_PRICE', 'ECOMMERCE_PRODUCT', 3),
    ('SALE_PRICE', 'INVENTORY_PRODUCT', 4),
    ('SIZE', 'ERP_PRODUCT', 1),
    ('SIZE', 'SUPPLIER_PRODUCT', 2),
    ('SIZE', 'ECOMMERCE_PRODUCT', 3),
    ('SIZE', 'INVENTORY_PRODUCT', 4);

INSERT INTO RELATIONSHIP_DISCOVERY_DB.MD.MD_ATTRIBUTE_MAPPING (CANONICAL_ATTRIBUTE, SOURCE_SYSTEM, SOURCE_ATTRIBUTE)
VALUES
    ('BRAND', 'ERP_PRODUCT', 'BRAND_NAME'),
    ('BRAND', 'SUPPLIER_PRODUCT', 'BRAND'),
    ('BRAND', 'INVENTORY_PRODUCT', 'BRAND_CODE'),
    ('BRAND', 'ECOMMERCE_PRODUCT', 'VENDOR_NAME'),
    ('PRODUCT_NAME', 'ERP_PRODUCT', 'PRODUCT_DESCRIPTION'),
    ('PRODUCT_NAME', 'SUPPLIER_PRODUCT', 'ITEM_NAME'),
    ('PRODUCT_NAME', 'INVENTORY_PRODUCT', 'SKU_DESCRIPTION'),
    ('PRODUCT_NAME', 'ECOMMERCE_PRODUCT', 'LISTING_TITLE'),
    ('CATEGORY', 'ERP_PRODUCT', 'PRODUCT_CATEGORY'),
    ('CATEGORY', 'SUPPLIER_PRODUCT', 'CATEGORY_DESCRIPTION'),
    ('CATEGORY', 'INVENTORY_PRODUCT', 'STORAGE_CATEGORY'),
    ('CATEGORY', 'ECOMMERCE_PRODUCT', 'WEB_CATEGORY'),
    ('MANUFACTURER', 'ERP_PRODUCT', 'MANUFACTURER_NAME'),
    ('MANUFACTURER', 'SUPPLIER_PRODUCT', 'MFG_NAME'),
    ('MANUFACTURER', 'INVENTORY_PRODUCT', 'BRAND_CODE'),
    ('MANUFACTURER', 'ECOMMERCE_PRODUCT', 'SELLER_NAME'),
    ('SALE_PRICE', 'ERP_PRODUCT', 'LIST_PRICE'),
    ('SALE_PRICE', 'SUPPLIER_PRODUCT', 'UNIT_COST'),
    ('SALE_PRICE', 'INVENTORY_PRODUCT', 'REORDER_COST'),
    ('SALE_PRICE', 'ECOMMERCE_PRODUCT', 'SELLING_PRICE'),
    ('SIZE', 'ERP_PRODUCT', 'PRODUCT_SIZE'),
    ('SIZE', 'SUPPLIER_PRODUCT', 'PACK_SIZE'),
    ('SIZE', 'INVENTORY_PRODUCT', 'WEIGHT_SIZE'),
    ('SIZE', 'ECOMMERCE_PRODUCT', 'DISPLAY_SIZE');
