INSERT INTO RELATIONSHIP_DISCOVERY_DB.LOG.ACTION_LOG (
    ACTION_TYPE,
    ACTION_STATUS,
    ACTIONED_FLAG,
    ENTITY_KEY,
    ERP_PRODUCT_ID,
    SUPPLIER_PRODUCT_ID,
    INVENTORY_PRODUCT_ID,
    ECOMMERCE_PRODUCT_ID,
    BRAND,
    PRODUCT_NAME,
    CATEGORY,
    MANUFACTURER,
    SALE_PRICE,
    SIZE,
    DERIVED_PRODUCT_FAMILY,
    DERIVED_PRODUCT_GROUP,
    DERIVED_PRODUCT_STATUS,
    SOURCE_EXECUTION_REFERENCE,
    ACTION_SOURCE
)
WITH dq_threshold AS (
    SELECT 60 AS MIN_DQ_SCORE
),

survivorship_config AS (
    SELECT ATTRIBUTE_NAME, SOURCE_SYSTEM, PRIORITY_ORDER
    FROM RELATIONSHIP_DISCOVERY_DB.MD.MD_ATTRIBUTE_SURVIVORSHIP
    WHERE ACTIVE_FLAG = 'Y'
),

brand_priority AS (
    SELECT SOURCE_SYSTEM, PRIORITY_ORDER FROM survivorship_config WHERE ATTRIBUTE_NAME = 'BRAND'
),
product_name_priority AS (
    SELECT SOURCE_SYSTEM, PRIORITY_ORDER FROM survivorship_config WHERE ATTRIBUTE_NAME = 'PRODUCT_NAME'
),
category_priority AS (
    SELECT SOURCE_SYSTEM, PRIORITY_ORDER FROM survivorship_config WHERE ATTRIBUTE_NAME = 'CATEGORY'
),
manufacturer_priority AS (
    SELECT SOURCE_SYSTEM, PRIORITY_ORDER FROM survivorship_config WHERE ATTRIBUTE_NAME = 'MANUFACTURER'
),
sale_price_priority AS (
    SELECT SOURCE_SYSTEM, PRIORITY_ORDER FROM survivorship_config WHERE ATTRIBUTE_NAME = 'SALE_PRICE'
),
size_priority AS (
    SELECT SOURCE_SYSTEM, PRIORITY_ORDER FROM survivorship_config WHERE ATTRIBUTE_NAME = 'SIZE'
),

normalized_source AS (
    SELECT
        ss.SOURCE_SYSTEM,
        ss.SOURCE_RECORD_ID,
        ss.BRAND,
        ss.PRODUCT_NAME,
        ss.CATEGORY,
        ss.MANUFACTURER,
        ss.SALE_PRICE,
        ss.SIZE,
        UPPER(TRIM(COALESCE(ss.BRAND, '')))        AS NORMALIZED_BRAND,
        UPPER(TRIM(COALESCE(ss.PRODUCT_NAME, ''))) AS NORMALIZED_PRODUCT_NAME,
        UPPER(TRIM(COALESCE(ss.SIZE, '')))         AS NORMALIZED_SIZE,
        COALESCE(dq.RECORD_DQ_SCORE, 0)           AS RECORD_DQ_SCORE
    FROM RELATIONSHIP_DISCOVERY_DB.INTM.SOURCE_SUPERSET ss
    LEFT JOIN RELATIONSHIP_DISCOVERY_DB.INTM.DQ_RECORD_SUMMARY dq
        ON ss.SOURCE_SYSTEM = dq.SOURCE_SYSTEM
        AND ss.SOURCE_RECORD_ID = dq.SOURCE_RECORD_ID
),

source_dedup AS (
    SELECT
        SOURCE_SYSTEM,
        SOURCE_RECORD_ID,
        BRAND,
        PRODUCT_NAME,
        CATEGORY,
        MANUFACTURER,
        SALE_PRICE,
        SIZE,
        NORMALIZED_BRAND,
        NORMALIZED_PRODUCT_NAME,
        NORMALIZED_SIZE,
        RECORD_DQ_SCORE,
        ROW_NUMBER() OVER (
            PARTITION BY SOURCE_SYSTEM, NORMALIZED_BRAND, NORMALIZED_PRODUCT_NAME, NORMALIZED_SIZE
            ORDER BY RECORD_DQ_SCORE DESC, SOURCE_RECORD_ID ASC
        ) AS DEDUP_RN
    FROM normalized_source
),

deduplicated AS (
    SELECT
        SOURCE_SYSTEM,
        SOURCE_RECORD_ID,
        BRAND,
        PRODUCT_NAME,
        CATEGORY,
        MANUFACTURER,
        SALE_PRICE,
        SIZE,
        NORMALIZED_BRAND,
        NORMALIZED_PRODUCT_NAME,
        NORMALIZED_SIZE,
        RECORD_DQ_SCORE
    FROM source_dedup
    WHERE DEDUP_RN = 1
),

erp_segment AS (
    SELECT * FROM deduplicated WHERE SOURCE_SYSTEM = 'ERP_PRODUCT'
),

supplier_segment AS (
    SELECT * FROM deduplicated WHERE SOURCE_SYSTEM = 'SUPPLIER_PRODUCT'
),

inventory_segment AS (
    SELECT * FROM deduplicated WHERE SOURCE_SYSTEM = 'INVENTORY_PRODUCT'
),

ecommerce_segment AS (
    SELECT * FROM deduplicated WHERE SOURCE_SYSTEM = 'ECOMMERCE_PRODUCT'
),

wide_entity AS (
    SELECT
        COALESCE(e.NORMALIZED_BRAND, s.NORMALIZED_BRAND, i.NORMALIZED_BRAND, ec.NORMALIZED_BRAND)                             AS NORMALIZED_BRAND,
        COALESCE(e.NORMALIZED_PRODUCT_NAME, s.NORMALIZED_PRODUCT_NAME, i.NORMALIZED_PRODUCT_NAME, ec.NORMALIZED_PRODUCT_NAME) AS NORMALIZED_PRODUCT_NAME,
        COALESCE(e.NORMALIZED_SIZE, s.NORMALIZED_SIZE, i.NORMALIZED_SIZE, ec.NORMALIZED_SIZE)                                 AS NORMALIZED_SIZE,
        e.SOURCE_RECORD_ID  AS ERP_PRODUCT_ID,
        e.BRAND             AS ERP_BRAND,
        e.PRODUCT_NAME      AS ERP_PRODUCT_NAME,
        e.CATEGORY          AS ERP_CATEGORY,
        e.MANUFACTURER      AS ERP_MANUFACTURER,
        e.SALE_PRICE        AS ERP_SALE_PRICE,
        e.SIZE              AS ERP_SIZE,
        e.RECORD_DQ_SCORE   AS ERP_DQ_SCORE,
        s.SOURCE_RECORD_ID  AS SUPPLIER_PRODUCT_ID,
        s.BRAND             AS SUPPLIER_BRAND,
        s.PRODUCT_NAME      AS SUPPLIER_PRODUCT_NAME,
        s.CATEGORY          AS SUPPLIER_CATEGORY,
        s.MANUFACTURER      AS SUPPLIER_MANUFACTURER,
        s.SALE_PRICE        AS SUPPLIER_SALE_PRICE,
        s.SIZE              AS SUPPLIER_SIZE,
        s.RECORD_DQ_SCORE   AS SUPPLIER_DQ_SCORE,
        i.SOURCE_RECORD_ID  AS INVENTORY_PRODUCT_ID,
        i.BRAND             AS INVENTORY_BRAND,
        i.PRODUCT_NAME      AS INVENTORY_PRODUCT_NAME,
        i.CATEGORY          AS INVENTORY_CATEGORY,
        i.MANUFACTURER      AS INVENTORY_MANUFACTURER,
        i.SALE_PRICE        AS INVENTORY_SALE_PRICE,
        i.SIZE              AS INVENTORY_SIZE,
        i.RECORD_DQ_SCORE   AS INVENTORY_DQ_SCORE,
        ec.SOURCE_RECORD_ID AS ECOMMERCE_PRODUCT_ID,
        ec.BRAND            AS ECOMMERCE_BRAND,
        ec.PRODUCT_NAME     AS ECOMMERCE_PRODUCT_NAME,
        ec.CATEGORY         AS ECOMMERCE_CATEGORY,
        ec.MANUFACTURER     AS ECOMMERCE_MANUFACTURER,
        ec.SALE_PRICE       AS ECOMMERCE_SALE_PRICE,
        ec.SIZE             AS ECOMMERCE_SIZE,
        ec.RECORD_DQ_SCORE  AS ECOMMERCE_DQ_SCORE,
        (CASE WHEN e.SOURCE_RECORD_ID IS NOT NULL THEN 1 ELSE 0 END
         + CASE WHEN s.SOURCE_RECORD_ID IS NOT NULL THEN 1 ELSE 0 END
         + CASE WHEN i.SOURCE_RECORD_ID IS NOT NULL THEN 1 ELSE 0 END
         + CASE WHEN ec.SOURCE_RECORD_ID IS NOT NULL THEN 1 ELSE 0 END) AS SOURCE_COVERAGE
    FROM erp_segment e
    FULL OUTER JOIN supplier_segment s
        ON e.NORMALIZED_BRAND = s.NORMALIZED_BRAND
        AND e.NORMALIZED_PRODUCT_NAME = s.NORMALIZED_PRODUCT_NAME
        AND e.NORMALIZED_SIZE = s.NORMALIZED_SIZE
    FULL OUTER JOIN inventory_segment i
        ON COALESCE(e.NORMALIZED_BRAND, s.NORMALIZED_BRAND) = i.NORMALIZED_BRAND
        AND COALESCE(e.NORMALIZED_PRODUCT_NAME, s.NORMALIZED_PRODUCT_NAME) = i.NORMALIZED_PRODUCT_NAME
        AND COALESCE(e.NORMALIZED_SIZE, s.NORMALIZED_SIZE) = i.NORMALIZED_SIZE
    FULL OUTER JOIN ecommerce_segment ec
        ON COALESCE(e.NORMALIZED_BRAND, s.NORMALIZED_BRAND, i.NORMALIZED_BRAND) = ec.NORMALIZED_BRAND
        AND COALESCE(e.NORMALIZED_PRODUCT_NAME, s.NORMALIZED_PRODUCT_NAME, i.NORMALIZED_PRODUCT_NAME) = ec.NORMALIZED_PRODUCT_NAME
        AND COALESCE(e.NORMALIZED_SIZE, s.NORMALIZED_SIZE, i.NORMALIZED_SIZE) = ec.NORMALIZED_SIZE
),

survivorship_applied AS (
    SELECT
        w.*,

        CASE LEAST(
            CASE WHEN w.ERP_BRAND IS NOT NULL AND TRIM(w.ERP_BRAND) != '' AND w.ERP_DQ_SCORE >= t.MIN_DQ_SCORE THEN bp_erp.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.SUPPLIER_BRAND IS NOT NULL AND TRIM(w.SUPPLIER_BRAND) != '' AND w.SUPPLIER_DQ_SCORE >= t.MIN_DQ_SCORE THEN bp_sup.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.INVENTORY_BRAND IS NOT NULL AND TRIM(w.INVENTORY_BRAND) != '' AND w.INVENTORY_DQ_SCORE >= t.MIN_DQ_SCORE THEN bp_inv.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.ECOMMERCE_BRAND IS NOT NULL AND TRIM(w.ECOMMERCE_BRAND) != '' AND w.ECOMMERCE_DQ_SCORE >= t.MIN_DQ_SCORE THEN bp_ecom.PRIORITY_ORDER ELSE 999 END
        )
            WHEN bp_erp.PRIORITY_ORDER  THEN w.ERP_BRAND
            WHEN bp_sup.PRIORITY_ORDER  THEN w.SUPPLIER_BRAND
            WHEN bp_inv.PRIORITY_ORDER  THEN w.INVENTORY_BRAND
            WHEN bp_ecom.PRIORITY_ORDER THEN w.ECOMMERCE_BRAND
            ELSE NULL
        END AS SURVIVED_BRAND,

        CASE LEAST(
            CASE WHEN w.ERP_BRAND IS NOT NULL AND TRIM(w.ERP_BRAND) != '' AND w.ERP_DQ_SCORE >= t.MIN_DQ_SCORE THEN bp_erp.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.SUPPLIER_BRAND IS NOT NULL AND TRIM(w.SUPPLIER_BRAND) != '' AND w.SUPPLIER_DQ_SCORE >= t.MIN_DQ_SCORE THEN bp_sup.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.INVENTORY_BRAND IS NOT NULL AND TRIM(w.INVENTORY_BRAND) != '' AND w.INVENTORY_DQ_SCORE >= t.MIN_DQ_SCORE THEN bp_inv.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.ECOMMERCE_BRAND IS NOT NULL AND TRIM(w.ECOMMERCE_BRAND) != '' AND w.ECOMMERCE_DQ_SCORE >= t.MIN_DQ_SCORE THEN bp_ecom.PRIORITY_ORDER ELSE 999 END
        )
            WHEN bp_erp.PRIORITY_ORDER  THEN 'ERP_PRODUCT'
            WHEN bp_sup.PRIORITY_ORDER  THEN 'SUPPLIER_PRODUCT'
            WHEN bp_inv.PRIORITY_ORDER  THEN 'INVENTORY_PRODUCT'
            WHEN bp_ecom.PRIORITY_ORDER THEN 'ECOMMERCE_PRODUCT'
            ELSE NULL
        END AS MASTER_BRAND_SOURCE,

        CASE LEAST(
            CASE WHEN w.ERP_PRODUCT_NAME IS NOT NULL AND TRIM(w.ERP_PRODUCT_NAME) != '' AND w.ERP_DQ_SCORE >= t.MIN_DQ_SCORE THEN pn_erp.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.SUPPLIER_PRODUCT_NAME IS NOT NULL AND TRIM(w.SUPPLIER_PRODUCT_NAME) != '' AND w.SUPPLIER_DQ_SCORE >= t.MIN_DQ_SCORE THEN pn_sup.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.INVENTORY_PRODUCT_NAME IS NOT NULL AND TRIM(w.INVENTORY_PRODUCT_NAME) != '' AND w.INVENTORY_DQ_SCORE >= t.MIN_DQ_SCORE THEN pn_inv.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.ECOMMERCE_PRODUCT_NAME IS NOT NULL AND TRIM(w.ECOMMERCE_PRODUCT_NAME) != '' AND w.ECOMMERCE_DQ_SCORE >= t.MIN_DQ_SCORE THEN pn_ecom.PRIORITY_ORDER ELSE 999 END
        )
            WHEN pn_erp.PRIORITY_ORDER  THEN w.ERP_PRODUCT_NAME
            WHEN pn_sup.PRIORITY_ORDER  THEN w.SUPPLIER_PRODUCT_NAME
            WHEN pn_inv.PRIORITY_ORDER  THEN w.INVENTORY_PRODUCT_NAME
            WHEN pn_ecom.PRIORITY_ORDER THEN w.ECOMMERCE_PRODUCT_NAME
            ELSE NULL
        END AS SURVIVED_PRODUCT_NAME,

        CASE LEAST(
            CASE WHEN w.ERP_PRODUCT_NAME IS NOT NULL AND TRIM(w.ERP_PRODUCT_NAME) != '' AND w.ERP_DQ_SCORE >= t.MIN_DQ_SCORE THEN pn_erp.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.SUPPLIER_PRODUCT_NAME IS NOT NULL AND TRIM(w.SUPPLIER_PRODUCT_NAME) != '' AND w.SUPPLIER_DQ_SCORE >= t.MIN_DQ_SCORE THEN pn_sup.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.INVENTORY_PRODUCT_NAME IS NOT NULL AND TRIM(w.INVENTORY_PRODUCT_NAME) != '' AND w.INVENTORY_DQ_SCORE >= t.MIN_DQ_SCORE THEN pn_inv.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.ECOMMERCE_PRODUCT_NAME IS NOT NULL AND TRIM(w.ECOMMERCE_PRODUCT_NAME) != '' AND w.ECOMMERCE_DQ_SCORE >= t.MIN_DQ_SCORE THEN pn_ecom.PRIORITY_ORDER ELSE 999 END
        )
            WHEN pn_erp.PRIORITY_ORDER  THEN 'ERP_PRODUCT'
            WHEN pn_sup.PRIORITY_ORDER  THEN 'SUPPLIER_PRODUCT'
            WHEN pn_inv.PRIORITY_ORDER  THEN 'INVENTORY_PRODUCT'
            WHEN pn_ecom.PRIORITY_ORDER THEN 'ECOMMERCE_PRODUCT'
            ELSE NULL
        END AS MASTER_PRODUCT_NAME_SOURCE,

        CASE LEAST(
            CASE WHEN w.ERP_CATEGORY IS NOT NULL AND TRIM(w.ERP_CATEGORY) != '' AND w.ERP_DQ_SCORE >= t.MIN_DQ_SCORE THEN cat_erp.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.SUPPLIER_CATEGORY IS NOT NULL AND TRIM(w.SUPPLIER_CATEGORY) != '' AND w.SUPPLIER_DQ_SCORE >= t.MIN_DQ_SCORE THEN cat_sup.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.INVENTORY_CATEGORY IS NOT NULL AND TRIM(w.INVENTORY_CATEGORY) != '' AND w.INVENTORY_DQ_SCORE >= t.MIN_DQ_SCORE THEN cat_inv.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.ECOMMERCE_CATEGORY IS NOT NULL AND TRIM(w.ECOMMERCE_CATEGORY) != '' AND w.ECOMMERCE_DQ_SCORE >= t.MIN_DQ_SCORE THEN cat_ecom.PRIORITY_ORDER ELSE 999 END
        )
            WHEN cat_erp.PRIORITY_ORDER  THEN w.ERP_CATEGORY
            WHEN cat_sup.PRIORITY_ORDER  THEN w.SUPPLIER_CATEGORY
            WHEN cat_inv.PRIORITY_ORDER  THEN w.INVENTORY_CATEGORY
            WHEN cat_ecom.PRIORITY_ORDER THEN w.ECOMMERCE_CATEGORY
            ELSE NULL
        END AS SURVIVED_CATEGORY,

        CASE LEAST(
            CASE WHEN w.ERP_CATEGORY IS NOT NULL AND TRIM(w.ERP_CATEGORY) != '' AND w.ERP_DQ_SCORE >= t.MIN_DQ_SCORE THEN cat_erp.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.SUPPLIER_CATEGORY IS NOT NULL AND TRIM(w.SUPPLIER_CATEGORY) != '' AND w.SUPPLIER_DQ_SCORE >= t.MIN_DQ_SCORE THEN cat_sup.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.INVENTORY_CATEGORY IS NOT NULL AND TRIM(w.INVENTORY_CATEGORY) != '' AND w.INVENTORY_DQ_SCORE >= t.MIN_DQ_SCORE THEN cat_inv.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.ECOMMERCE_CATEGORY IS NOT NULL AND TRIM(w.ECOMMERCE_CATEGORY) != '' AND w.ECOMMERCE_DQ_SCORE >= t.MIN_DQ_SCORE THEN cat_ecom.PRIORITY_ORDER ELSE 999 END
        )
            WHEN cat_erp.PRIORITY_ORDER  THEN 'ERP_PRODUCT'
            WHEN cat_sup.PRIORITY_ORDER  THEN 'SUPPLIER_PRODUCT'
            WHEN cat_inv.PRIORITY_ORDER  THEN 'INVENTORY_PRODUCT'
            WHEN cat_ecom.PRIORITY_ORDER THEN 'ECOMMERCE_PRODUCT'
            ELSE NULL
        END AS MASTER_CATEGORY_SOURCE,

        CASE LEAST(
            CASE WHEN w.ERP_MANUFACTURER IS NOT NULL AND TRIM(w.ERP_MANUFACTURER) != '' AND w.ERP_DQ_SCORE >= t.MIN_DQ_SCORE THEN mfr_erp.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.SUPPLIER_MANUFACTURER IS NOT NULL AND TRIM(w.SUPPLIER_MANUFACTURER) != '' AND w.SUPPLIER_DQ_SCORE >= t.MIN_DQ_SCORE THEN mfr_sup.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.INVENTORY_MANUFACTURER IS NOT NULL AND TRIM(w.INVENTORY_MANUFACTURER) != '' AND w.INVENTORY_DQ_SCORE >= t.MIN_DQ_SCORE THEN mfr_inv.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.ECOMMERCE_MANUFACTURER IS NOT NULL AND TRIM(w.ECOMMERCE_MANUFACTURER) != '' AND w.ECOMMERCE_DQ_SCORE >= t.MIN_DQ_SCORE THEN mfr_ecom.PRIORITY_ORDER ELSE 999 END
        )
            WHEN mfr_erp.PRIORITY_ORDER  THEN w.ERP_MANUFACTURER
            WHEN mfr_sup.PRIORITY_ORDER  THEN w.SUPPLIER_MANUFACTURER
            WHEN mfr_inv.PRIORITY_ORDER  THEN w.INVENTORY_MANUFACTURER
            WHEN mfr_ecom.PRIORITY_ORDER THEN w.ECOMMERCE_MANUFACTURER
            ELSE NULL
        END AS SURVIVED_MANUFACTURER,

        CASE LEAST(
            CASE WHEN w.ERP_MANUFACTURER IS NOT NULL AND TRIM(w.ERP_MANUFACTURER) != '' AND w.ERP_DQ_SCORE >= t.MIN_DQ_SCORE THEN mfr_erp.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.SUPPLIER_MANUFACTURER IS NOT NULL AND TRIM(w.SUPPLIER_MANUFACTURER) != '' AND w.SUPPLIER_DQ_SCORE >= t.MIN_DQ_SCORE THEN mfr_sup.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.INVENTORY_MANUFACTURER IS NOT NULL AND TRIM(w.INVENTORY_MANUFACTURER) != '' AND w.INVENTORY_DQ_SCORE >= t.MIN_DQ_SCORE THEN mfr_inv.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.ECOMMERCE_MANUFACTURER IS NOT NULL AND TRIM(w.ECOMMERCE_MANUFACTURER) != '' AND w.ECOMMERCE_DQ_SCORE >= t.MIN_DQ_SCORE THEN mfr_ecom.PRIORITY_ORDER ELSE 999 END
        )
            WHEN mfr_erp.PRIORITY_ORDER  THEN 'ERP_PRODUCT'
            WHEN mfr_sup.PRIORITY_ORDER  THEN 'SUPPLIER_PRODUCT'
            WHEN mfr_inv.PRIORITY_ORDER  THEN 'INVENTORY_PRODUCT'
            WHEN mfr_ecom.PRIORITY_ORDER THEN 'ECOMMERCE_PRODUCT'
            ELSE NULL
        END AS MASTER_MANUFACTURER_SOURCE,

        CASE LEAST(
            CASE WHEN w.ERP_SALE_PRICE IS NOT NULL AND w.ERP_DQ_SCORE >= t.MIN_DQ_SCORE THEN sp_erp.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.SUPPLIER_SALE_PRICE IS NOT NULL AND w.SUPPLIER_DQ_SCORE >= t.MIN_DQ_SCORE THEN sp_sup.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.INVENTORY_SALE_PRICE IS NOT NULL AND w.INVENTORY_DQ_SCORE >= t.MIN_DQ_SCORE THEN sp_inv.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.ECOMMERCE_SALE_PRICE IS NOT NULL AND w.ECOMMERCE_DQ_SCORE >= t.MIN_DQ_SCORE THEN sp_ecom.PRIORITY_ORDER ELSE 999 END
        )
            WHEN sp_erp.PRIORITY_ORDER  THEN w.ERP_SALE_PRICE
            WHEN sp_sup.PRIORITY_ORDER  THEN w.SUPPLIER_SALE_PRICE
            WHEN sp_inv.PRIORITY_ORDER  THEN w.INVENTORY_SALE_PRICE
            WHEN sp_ecom.PRIORITY_ORDER THEN w.ECOMMERCE_SALE_PRICE
            ELSE NULL
        END AS SURVIVED_SALE_PRICE,

        CASE LEAST(
            CASE WHEN w.ERP_SALE_PRICE IS NOT NULL AND w.ERP_DQ_SCORE >= t.MIN_DQ_SCORE THEN sp_erp.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.SUPPLIER_SALE_PRICE IS NOT NULL AND w.SUPPLIER_DQ_SCORE >= t.MIN_DQ_SCORE THEN sp_sup.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.INVENTORY_SALE_PRICE IS NOT NULL AND w.INVENTORY_DQ_SCORE >= t.MIN_DQ_SCORE THEN sp_inv.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.ECOMMERCE_SALE_PRICE IS NOT NULL AND w.ECOMMERCE_DQ_SCORE >= t.MIN_DQ_SCORE THEN sp_ecom.PRIORITY_ORDER ELSE 999 END
        )
            WHEN sp_erp.PRIORITY_ORDER  THEN 'ERP_PRODUCT'
            WHEN sp_sup.PRIORITY_ORDER  THEN 'SUPPLIER_PRODUCT'
            WHEN sp_inv.PRIORITY_ORDER  THEN 'INVENTORY_PRODUCT'
            WHEN sp_ecom.PRIORITY_ORDER THEN 'ECOMMERCE_PRODUCT'
            ELSE NULL
        END AS MASTER_SALE_PRICE_SOURCE,

        CASE LEAST(
            CASE WHEN w.ERP_SIZE IS NOT NULL AND TRIM(w.ERP_SIZE) != '' AND w.ERP_DQ_SCORE >= t.MIN_DQ_SCORE THEN sz_erp.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.SUPPLIER_SIZE IS NOT NULL AND TRIM(w.SUPPLIER_SIZE) != '' AND w.SUPPLIER_DQ_SCORE >= t.MIN_DQ_SCORE THEN sz_sup.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.INVENTORY_SIZE IS NOT NULL AND TRIM(w.INVENTORY_SIZE) != '' AND w.INVENTORY_DQ_SCORE >= t.MIN_DQ_SCORE THEN sz_inv.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.ECOMMERCE_SIZE IS NOT NULL AND TRIM(w.ECOMMERCE_SIZE) != '' AND w.ECOMMERCE_DQ_SCORE >= t.MIN_DQ_SCORE THEN sz_ecom.PRIORITY_ORDER ELSE 999 END
        )
            WHEN sz_erp.PRIORITY_ORDER  THEN w.ERP_SIZE
            WHEN sz_sup.PRIORITY_ORDER  THEN w.SUPPLIER_SIZE
            WHEN sz_inv.PRIORITY_ORDER  THEN w.INVENTORY_SIZE
            WHEN sz_ecom.PRIORITY_ORDER THEN w.ECOMMERCE_SIZE
            ELSE NULL
        END AS SURVIVED_SIZE,

        CASE LEAST(
            CASE WHEN w.ERP_SIZE IS NOT NULL AND TRIM(w.ERP_SIZE) != '' AND w.ERP_DQ_SCORE >= t.MIN_DQ_SCORE THEN sz_erp.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.SUPPLIER_SIZE IS NOT NULL AND TRIM(w.SUPPLIER_SIZE) != '' AND w.SUPPLIER_DQ_SCORE >= t.MIN_DQ_SCORE THEN sz_sup.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.INVENTORY_SIZE IS NOT NULL AND TRIM(w.INVENTORY_SIZE) != '' AND w.INVENTORY_DQ_SCORE >= t.MIN_DQ_SCORE THEN sz_inv.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.ECOMMERCE_SIZE IS NOT NULL AND TRIM(w.ECOMMERCE_SIZE) != '' AND w.ECOMMERCE_DQ_SCORE >= t.MIN_DQ_SCORE THEN sz_ecom.PRIORITY_ORDER ELSE 999 END
        )
            WHEN sz_erp.PRIORITY_ORDER  THEN 'ERP_PRODUCT'
            WHEN sz_sup.PRIORITY_ORDER  THEN 'SUPPLIER_PRODUCT'
            WHEN sz_inv.PRIORITY_ORDER  THEN 'INVENTORY_PRODUCT'
            WHEN sz_ecom.PRIORITY_ORDER THEN 'ECOMMERCE_PRODUCT'
            ELSE NULL
        END AS MASTER_SIZE_SOURCE,

        CASE LEAST(
            CASE WHEN w.ERP_CATEGORY IS NOT NULL AND TRIM(w.ERP_CATEGORY) != '' THEN cat_erp.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.SUPPLIER_CATEGORY IS NOT NULL AND TRIM(w.SUPPLIER_CATEGORY) != '' THEN cat_sup.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.INVENTORY_CATEGORY IS NOT NULL AND TRIM(w.INVENTORY_CATEGORY) != '' THEN cat_inv.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.ECOMMERCE_CATEGORY IS NOT NULL AND TRIM(w.ECOMMERCE_CATEGORY) != '' THEN cat_ecom.PRIORITY_ORDER ELSE 999 END
        )
            WHEN cat_erp.PRIORITY_ORDER  THEN w.ERP_CATEGORY
            WHEN cat_sup.PRIORITY_ORDER  THEN w.SUPPLIER_CATEGORY
            WHEN cat_inv.PRIORITY_ORDER  THEN w.INVENTORY_CATEGORY
            WHEN cat_ecom.PRIORITY_ORDER THEN w.ECOMMERCE_CATEGORY
            ELSE NULL
        END AS FALLBACK_CATEGORY,

        CASE LEAST(
            CASE WHEN w.ERP_MANUFACTURER IS NOT NULL AND TRIM(w.ERP_MANUFACTURER) != '' THEN mfr_erp.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.SUPPLIER_MANUFACTURER IS NOT NULL AND TRIM(w.SUPPLIER_MANUFACTURER) != '' THEN mfr_sup.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.INVENTORY_MANUFACTURER IS NOT NULL AND TRIM(w.INVENTORY_MANUFACTURER) != '' THEN mfr_inv.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.ECOMMERCE_MANUFACTURER IS NOT NULL AND TRIM(w.ECOMMERCE_MANUFACTURER) != '' THEN mfr_ecom.PRIORITY_ORDER ELSE 999 END
        )
            WHEN mfr_erp.PRIORITY_ORDER  THEN w.ERP_MANUFACTURER
            WHEN mfr_sup.PRIORITY_ORDER  THEN w.SUPPLIER_MANUFACTURER
            WHEN mfr_inv.PRIORITY_ORDER  THEN w.INVENTORY_MANUFACTURER
            WHEN mfr_ecom.PRIORITY_ORDER THEN w.ECOMMERCE_MANUFACTURER
            ELSE NULL
        END AS FALLBACK_MANUFACTURER,

        CASE LEAST(
            CASE WHEN w.ERP_SALE_PRICE IS NOT NULL THEN sp_erp.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.SUPPLIER_SALE_PRICE IS NOT NULL THEN sp_sup.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.INVENTORY_SALE_PRICE IS NOT NULL THEN sp_inv.PRIORITY_ORDER ELSE 999 END,
            CASE WHEN w.ECOMMERCE_SALE_PRICE IS NOT NULL THEN sp_ecom.PRIORITY_ORDER ELSE 999 END
        )
            WHEN sp_erp.PRIORITY_ORDER  THEN w.ERP_SALE_PRICE
            WHEN sp_sup.PRIORITY_ORDER  THEN w.SUPPLIER_SALE_PRICE
            WHEN sp_inv.PRIORITY_ORDER  THEN w.INVENTORY_SALE_PRICE
            WHEN sp_ecom.PRIORITY_ORDER THEN w.ECOMMERCE_SALE_PRICE
            ELSE NULL
        END AS FALLBACK_SALE_PRICE,

        (COALESCE(w.ERP_DQ_SCORE, 0) + COALESCE(w.SUPPLIER_DQ_SCORE, 0)
         + COALESCE(w.INVENTORY_DQ_SCORE, 0) + COALESCE(w.ECOMMERCE_DQ_SCORE, 0))
        / NULLIF(
            (CASE WHEN w.ERP_DQ_SCORE > 0 THEN 1 ELSE 0 END
             + CASE WHEN w.SUPPLIER_DQ_SCORE > 0 THEN 1 ELSE 0 END
             + CASE WHEN w.INVENTORY_DQ_SCORE > 0 THEN 1 ELSE 0 END
             + CASE WHEN w.ECOMMERCE_DQ_SCORE > 0 THEN 1 ELSE 0 END), 0
        ) AS AVG_RECORD_DQ_SCORE

    FROM wide_entity w
    CROSS JOIN dq_threshold t
    LEFT JOIN brand_priority bp_erp  ON bp_erp.SOURCE_SYSTEM  = 'ERP_PRODUCT'
    LEFT JOIN brand_priority bp_sup  ON bp_sup.SOURCE_SYSTEM  = 'SUPPLIER_PRODUCT'
    LEFT JOIN brand_priority bp_inv  ON bp_inv.SOURCE_SYSTEM  = 'INVENTORY_PRODUCT'
    LEFT JOIN brand_priority bp_ecom ON bp_ecom.SOURCE_SYSTEM = 'ECOMMERCE_PRODUCT'
    LEFT JOIN product_name_priority pn_erp  ON pn_erp.SOURCE_SYSTEM  = 'ERP_PRODUCT'
    LEFT JOIN product_name_priority pn_sup  ON pn_sup.SOURCE_SYSTEM  = 'SUPPLIER_PRODUCT'
    LEFT JOIN product_name_priority pn_inv  ON pn_inv.SOURCE_SYSTEM  = 'INVENTORY_PRODUCT'
    LEFT JOIN product_name_priority pn_ecom ON pn_ecom.SOURCE_SYSTEM = 'ECOMMERCE_PRODUCT'
    LEFT JOIN category_priority cat_erp  ON cat_erp.SOURCE_SYSTEM  = 'ERP_PRODUCT'
    LEFT JOIN category_priority cat_sup  ON cat_sup.SOURCE_SYSTEM  = 'SUPPLIER_PRODUCT'
    LEFT JOIN category_priority cat_inv  ON cat_inv.SOURCE_SYSTEM  = 'INVENTORY_PRODUCT'
    LEFT JOIN category_priority cat_ecom ON cat_ecom.SOURCE_SYSTEM = 'ECOMMERCE_PRODUCT'
    LEFT JOIN manufacturer_priority mfr_erp  ON mfr_erp.SOURCE_SYSTEM  = 'ERP_PRODUCT'
    LEFT JOIN manufacturer_priority mfr_sup  ON mfr_sup.SOURCE_SYSTEM  = 'SUPPLIER_PRODUCT'
    LEFT JOIN manufacturer_priority mfr_inv  ON mfr_inv.SOURCE_SYSTEM  = 'INVENTORY_PRODUCT'
    LEFT JOIN manufacturer_priority mfr_ecom ON mfr_ecom.SOURCE_SYSTEM = 'ECOMMERCE_PRODUCT'
    LEFT JOIN sale_price_priority sp_erp  ON sp_erp.SOURCE_SYSTEM  = 'ERP_PRODUCT'
    LEFT JOIN sale_price_priority sp_sup  ON sp_sup.SOURCE_SYSTEM  = 'SUPPLIER_PRODUCT'
    LEFT JOIN sale_price_priority sp_inv  ON sp_inv.SOURCE_SYSTEM  = 'INVENTORY_PRODUCT'
    LEFT JOIN sale_price_priority sp_ecom ON sp_ecom.SOURCE_SYSTEM = 'ECOMMERCE_PRODUCT'
    LEFT JOIN size_priority sz_erp  ON sz_erp.SOURCE_SYSTEM  = 'ERP_PRODUCT'
    LEFT JOIN size_priority sz_sup  ON sz_sup.SOURCE_SYSTEM  = 'SUPPLIER_PRODUCT'
    LEFT JOIN size_priority sz_inv  ON sz_inv.SOURCE_SYSTEM  = 'INVENTORY_PRODUCT'
    LEFT JOIN size_priority sz_ecom ON sz_ecom.SOURCE_SYSTEM = 'ECOMMERCE_PRODUCT'
),

master_candidates AS (
    SELECT
        sa.*,
        COALESCE(sa.SURVIVED_BRAND, sa.NORMALIZED_BRAND)               AS MASTER_BRAND,
        COALESCE(sa.SURVIVED_PRODUCT_NAME, sa.NORMALIZED_PRODUCT_NAME) AS MASTER_PRODUCT_NAME,
        COALESCE(sa.SURVIVED_SIZE, sa.NORMALIZED_SIZE)                 AS MASTER_SIZE,
        COALESCE(sa.SURVIVED_CATEGORY, sa.FALLBACK_CATEGORY)           AS MASTER_CATEGORY,
        COALESCE(sa.SURVIVED_MANUFACTURER, sa.FALLBACK_MANUFACTURER)   AS MASTER_MANUFACTURER,
        COALESCE(sa.SURVIVED_SALE_PRICE, sa.FALLBACK_SALE_PRICE)       AS MASTER_SALE_PRICE
    FROM survivorship_applied sa
),

final_master_dedup AS (
    SELECT
        mc.*,
        ROW_NUMBER() OVER (
            PARTITION BY UPPER(TRIM(mc.MASTER_BRAND)),
                         UPPER(TRIM(mc.MASTER_PRODUCT_NAME)),
                         UPPER(TRIM(mc.MASTER_SIZE))
            ORDER BY mc.SOURCE_COVERAGE DESC,
                     mc.AVG_RECORD_DQ_SCORE DESC NULLS LAST,
                     LEAST(
                         COALESCE(mc.ERP_PRODUCT_ID, 'ZZZZZZZZ'),
                         COALESCE(mc.SUPPLIER_PRODUCT_ID, 'ZZZZZZZZ'),
                         COALESCE(mc.INVENTORY_PRODUCT_ID, 'ZZZZZZZZ'),
                         COALESCE(mc.ECOMMERCE_PRODUCT_ID, 'ZZZZZZZZ')
                     ) ASC
        ) AS MASTER_DEDUP_RN
    FROM master_candidates mc
),

quality_gate AS (
    SELECT
        MD5_HEX(
            UPPER(TRIM(fm.MASTER_BRAND))
            || '|'
            || UPPER(TRIM(fm.MASTER_PRODUCT_NAME))
            || '|'
            || UPPER(TRIM(fm.MASTER_SIZE))
        ) AS ENTITY_KEY,
        fm.ERP_PRODUCT_ID,
        fm.SUPPLIER_PRODUCT_ID,
        fm.INVENTORY_PRODUCT_ID,
        fm.ECOMMERCE_PRODUCT_ID,
        fm.MASTER_BRAND,
        fm.MASTER_PRODUCT_NAME,
        fm.MASTER_CATEGORY,
        fm.MASTER_MANUFACTURER,
        fm.MASTER_SALE_PRICE,
        fm.MASTER_SIZE,
        fm.SOURCE_COVERAGE,
        fm.AVG_RECORD_DQ_SCORE,
        fm.MASTER_BRAND_SOURCE,
        fm.MASTER_PRODUCT_NAME_SOURCE,
        fm.MASTER_CATEGORY_SOURCE,
        fm.MASTER_MANUFACTURER_SOURCE,
        fm.MASTER_SALE_PRICE_SOURCE,
        fm.MASTER_SIZE_SOURCE
    FROM final_master_dedup fm
    WHERE fm.MASTER_DEDUP_RN = 1
      AND fm.MASTER_BRAND IS NOT NULL AND TRIM(fm.MASTER_BRAND) != ''
      AND fm.MASTER_PRODUCT_NAME IS NOT NULL AND TRIM(fm.MASTER_PRODUCT_NAME) != ''
      AND fm.MASTER_SIZE IS NOT NULL AND TRIM(fm.MASTER_SIZE) != ''
),

uniqueness_guard AS (
    SELECT
        qg.*,
        ROW_NUMBER() OVER (
            PARTITION BY qg.ENTITY_KEY
            ORDER BY qg.SOURCE_COVERAGE DESC,
                     qg.AVG_RECORD_DQ_SCORE DESC
        ) AS UNIQUE_RN
    FROM quality_gate qg
)

SELECT
    'CREATE'                AS ACTION_TYPE,
    'PENDING'               AS ACTION_STATUS,
    'N'                     AS ACTIONED_FLAG,
    ug.ENTITY_KEY,
    ug.ERP_PRODUCT_ID,
    ug.SUPPLIER_PRODUCT_ID,
    ug.INVENTORY_PRODUCT_ID,
    ug.ECOMMERCE_PRODUCT_ID,
    ug.MASTER_BRAND,
    ug.MASTER_PRODUCT_NAME,
    ug.MASTER_CATEGORY,
    ug.MASTER_MANUFACTURER,
    ug.MASTER_SALE_PRICE,
    ug.MASTER_SIZE,
    NULL                    AS DERIVED_PRODUCT_FAMILY,
    NULL                    AS DERIVED_PRODUCT_GROUP,
    NULL                    AS DERIVED_PRODUCT_STATUS,
    'BRAND_SRC:' || COALESCE(ug.MASTER_BRAND_SOURCE, 'FALLBACK')
        || '|NAME_SRC:' || COALESCE(ug.MASTER_PRODUCT_NAME_SOURCE, 'FALLBACK')
        || '|CAT_SRC:' || COALESCE(ug.MASTER_CATEGORY_SOURCE, 'FALLBACK')
        || '|MFR_SRC:' || COALESCE(ug.MASTER_MANUFACTURER_SOURCE, 'FALLBACK')
        || '|PRICE_SRC:' || COALESCE(ug.MASTER_SALE_PRICE_SOURCE, 'FALLBACK')
        || '|SIZE_SRC:' || COALESCE(ug.MASTER_SIZE_SOURCE, 'FALLBACK')
    AS SOURCE_EXECUTION_REFERENCE,
    'P_010_GENERATE_MASTER_CANDIDATE' AS ACTION_SOURCE
FROM uniqueness_guard ug
WHERE ug.UNIQUE_RN = 1
  AND NOT EXISTS (
    SELECT 1
    FROM RELATIONSHIP_DISCOVERY_DB.LOG.ACTION_LOG al
    WHERE al.ACTION_TYPE = 'CREATE'
      AND al.ENTITY_KEY = ug.ENTITY_KEY
);
