CREATE DATABASE IF NOT EXISTS RELATIONSHIP_DISCOVERY_DB;

CREATE SCHEMA IF NOT EXISTS RELATIONSHIP_DISCOVERY_DB.SRC;
CREATE SCHEMA IF NOT EXISTS RELATIONSHIP_DISCOVERY_DB.MD;
CREATE SCHEMA IF NOT EXISTS RELATIONSHIP_DISCOVERY_DB.LOG;
CREATE SCHEMA IF NOT EXISTS RELATIONSHIP_DISCOVERY_DB.INTM;
CREATE SCHEMA IF NOT EXISTS RELATIONSHIP_DISCOVERY_DB.FINAL;
CREATE SCHEMA IF NOT EXISTS RELATIONSHIP_DISCOVERY_DB.RPT;
