CREATE TABLE IF NOT EXISTS RELATIONSHIP_DISCOVERY_DB.INTM.SOURCE_SUPERSET (
    SOURCE_SUPERSET_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    SOURCE_SYSTEM VARCHAR(100) NOT NULL,
    SOURCE_RECORD_ID VARCHAR(100) NOT NULL,
    BRAND VARCHAR(500),
    PRODUCT_NAME VARCHAR(1000),
    CATEGORY VARCHAR(500),
    MANUFACTURER VARCHAR(500),
    SALE_PRICE NUMBER(18,2),
    SIZE VARCHAR(200),
    LOAD_DTTM TIMESTAMP,
    CREATED_DTTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO RELATIONSHIP_DISCOVERY_DB.INTM.SOURCE_SUPERSET (SOURCE_SYSTEM, SOURCE_RECORD_ID, BRAND, PRODUCT_NAME, CATEGORY, MANUFACTURER, SALE_PRICE, SIZE, LOAD_DTTM)
SELECT
    'ERP_PRODUCT',
    ERP_PRODUCT_ID::VARCHAR,
    BRAND_NAME,
    PRODUCT_DESCRIPTION,
    PRODUCT_CATEGORY,
    MANUFACTURER_NAME,
    LIST_PRICE,
    PRODUCT_SIZE,
    LOAD_DTTM
FROM RELATIONSHIP_DISCOVERY_DB.SRC.ERP_PRODUCT;

INSERT INTO RELATIONSHIP_DISCOVERY_DB.INTM.SOURCE_SUPERSET (SOURCE_SYSTEM, SOURCE_RECORD_ID, BRAND, PRODUCT_NAME, CATEGORY, MANUFACTURER, SALE_PRICE, SIZE, LOAD_DTTM)
SELECT
    'SUPPLIER_PRODUCT',
    SUPPLIER_PRODUCT_ID::VARCHAR,
    BRAND,
    ITEM_NAME,
    CATEGORY_DESCRIPTION,
    MFG_NAME,
    UNIT_COST,
    PACK_SIZE,
    LOAD_DTTM
FROM RELATIONSHIP_DISCOVERY_DB.SRC.SUPPLIER_PRODUCT;

INSERT INTO RELATIONSHIP_DISCOVERY_DB.INTM.SOURCE_SUPERSET (SOURCE_SYSTEM, SOURCE_RECORD_ID, BRAND, PRODUCT_NAME, CATEGORY, MANUFACTURER, SALE_PRICE, SIZE, LOAD_DTTM)
SELECT
    'INVENTORY_PRODUCT',
    INVENTORY_PRODUCT_ID::VARCHAR,
    BRAND_CODE,
    SKU_DESCRIPTION,
    STORAGE_CATEGORY,
    BRAND_CODE,
    REORDER_COST,
    WEIGHT_SIZE,
    LOAD_DTTM
FROM RELATIONSHIP_DISCOVERY_DB.SRC.INVENTORY_PRODUCT;

INSERT INTO RELATIONSHIP_DISCOVERY_DB.INTM.SOURCE_SUPERSET (SOURCE_SYSTEM, SOURCE_RECORD_ID, BRAND, PRODUCT_NAME, CATEGORY, MANUFACTURER, SALE_PRICE, SIZE, LOAD_DTTM)
SELECT
    'ECOMMERCE_PRODUCT',
    ECOMMERCE_PRODUCT_ID::VARCHAR,
    VENDOR_NAME,
    LISTING_TITLE,
    WEB_CATEGORY,
    SELLER_NAME,
    SELLING_PRICE,
    DISPLAY_SIZE,
    LOAD_DTTM
FROM RELATIONSHIP_DISCOVERY_DB.SRC.ECOMMERCE_PRODUCT;
