CREATE OR REPLACE TABLE RELATIONSHIP_DISCOVERY_DB.INTM.SOURCE_SUPERSET AS
SELECT
    ROW_NUMBER() OVER (ORDER BY SOURCE_SYSTEM, SOURCE_RECORD_ID) AS SOURCE_SUPERSET_ID,
    SOURCE_SYSTEM,
    SOURCE_RECORD_ID,
    BRAND,
    PRODUCT_NAME,
    CATEGORY,
    MANUFACTURER,
    SALE_PRICE,
    SIZE,
    LOAD_DTTM,
    CURRENT_TIMESTAMP() AS CREATED_DTTM
FROM (
    SELECT
        'ERP_PRODUCT' AS SOURCE_SYSTEM,
        ERP_PRODUCT_ID::VARCHAR AS SOURCE_RECORD_ID,
        BRAND_NAME AS BRAND,
        PRODUCT_DESCRIPTION AS PRODUCT_NAME,
        PRODUCT_CATEGORY AS CATEGORY,
        MANUFACTURER_NAME AS MANUFACTURER,
        LIST_PRICE AS SALE_PRICE,
        PRODUCT_SIZE AS SIZE,
        LOAD_DTTM
    FROM RELATIONSHIP_DISCOVERY_DB.SRC.ERP_PRODUCT
    UNION ALL
    SELECT
        'SUPPLIER_PRODUCT' AS SOURCE_SYSTEM,
        SUPPLIER_PRODUCT_ID::VARCHAR AS SOURCE_RECORD_ID,
        BRAND AS BRAND,
        ITEM_NAME AS PRODUCT_NAME,
        CATEGORY_DESCRIPTION AS CATEGORY,
        MFG_NAME AS MANUFACTURER,
        UNIT_COST AS SALE_PRICE,
        PACK_SIZE AS SIZE,
        LOAD_DTTM
    FROM RELATIONSHIP_DISCOVERY_DB.SRC.SUPPLIER_PRODUCT
    UNION ALL
    SELECT
        'INVENTORY_PRODUCT' AS SOURCE_SYSTEM,
        INVENTORY_PRODUCT_ID::VARCHAR AS SOURCE_RECORD_ID,
        BRAND_CODE AS BRAND,
        SKU_DESCRIPTION AS PRODUCT_NAME,
        STORAGE_CATEGORY AS CATEGORY,
        BRAND_CODE AS MANUFACTURER,
        REORDER_COST AS SALE_PRICE,
        WEIGHT_SIZE AS SIZE,
        LOAD_DTTM
    FROM RELATIONSHIP_DISCOVERY_DB.SRC.INVENTORY_PRODUCT
    UNION ALL
    SELECT
        'ECOMMERCE_PRODUCT' AS SOURCE_SYSTEM,
        ECOMMERCE_PRODUCT_ID::VARCHAR AS SOURCE_RECORD_ID,
        VENDOR_NAME AS BRAND,
        LISTING_TITLE AS PRODUCT_NAME,
        WEB_CATEGORY AS CATEGORY,
        SELLER_NAME AS MANUFACTURER,
        SELLING_PRICE AS SALE_PRICE,
        DISPLAY_SIZE AS SIZE,
        LOAD_DTTM
    FROM RELATIONSHIP_DISCOVERY_DB.SRC.ECOMMERCE_PRODUCT
);
