CREATE OR REPLACE TABLE RELATIONSHIP_DISCOVERY_DB.INTM.RELATIONSHIP_CANDIDATES AS
WITH BLOCKED_PAIRS AS (
    SELECT
        L.SOURCE_SYSTEM AS LEFT_SOURCE_SYSTEM,
        L.SOURCE_RECORD_ID AS LEFT_SOURCE_RECORD_ID,
        L.BRAND AS LEFT_BRAND,
        L.PRODUCT_NAME AS LEFT_PRODUCT_NAME,
        R.SOURCE_SYSTEM AS RIGHT_SOURCE_SYSTEM,
        R.SOURCE_RECORD_ID AS RIGHT_SOURCE_RECORD_ID,
        R.BRAND AS RIGHT_BRAND,
        R.PRODUCT_NAME AS RIGHT_PRODUCT_NAME
    FROM RELATIONSHIP_DISCOVERY_DB.INTM.SOURCE_SUPERSET L
    INNER JOIN RELATIONSHIP_DISCOVERY_DB.INTM.SOURCE_SUPERSET R
        ON L.SOURCE_SYSTEM < R.SOURCE_SYSTEM
        AND (
            LEFT(UPPER(TRIM(L.BRAND)), 3) = LEFT(UPPER(TRIM(R.BRAND)), 3)
            OR LEFT(UPPER(TRIM(L.PRODUCT_NAME)), 3) = LEFT(UPPER(TRIM(R.PRODUCT_NAME)), 3)
        )
    WHERE LENGTH(TRIM(COALESCE(L.BRAND, ''))) >= 3
        OR LENGTH(TRIM(COALESCE(L.PRODUCT_NAME, ''))) >= 3
),
SCORED AS (
    SELECT
        LEFT_SOURCE_SYSTEM,
        LEFT_SOURCE_RECORD_ID,
        RIGHT_SOURCE_SYSTEM,
        RIGHT_SOURCE_RECORD_ID,
        CASE
            WHEN UPPER(TRIM(LEFT_BRAND)) = UPPER(TRIM(RIGHT_BRAND))
                AND UPPER(TRIM(LEFT_PRODUCT_NAME)) = UPPER(TRIM(RIGHT_PRODUCT_NAME))
                THEN 'T0'
            WHEN (LENGTH(TRIM(LEFT_PRODUCT_NAME)) > 0 AND LENGTH(TRIM(RIGHT_PRODUCT_NAME)) > 0
                AND (UPPER(TRIM(LEFT_PRODUCT_NAME)) LIKE '%' || UPPER(TRIM(RIGHT_PRODUCT_NAME)) || '%'
                    OR UPPER(TRIM(RIGHT_PRODUCT_NAME)) LIKE '%' || UPPER(TRIM(LEFT_PRODUCT_NAME)) || '%'))
                THEN 'T1'
            WHEN (LENGTH(TRIM(LEFT_BRAND)) > 0 AND LENGTH(TRIM(RIGHT_BRAND)) > 0
                AND UPPER(TRIM(LEFT_BRAND)) != UPPER(TRIM(RIGHT_BRAND))
                AND (UPPER(TRIM(LEFT_BRAND)) LIKE '%' || UPPER(TRIM(RIGHT_BRAND)) || '%'
                    OR UPPER(TRIM(RIGHT_BRAND)) LIKE '%' || UPPER(TRIM(LEFT_BRAND)) || '%'))
                THEN 'T1'
            WHEN (LENGTH(TRIM(LEFT_BRAND)) >= 3 AND LENGTH(TRIM(RIGHT_BRAND)) >= 3
                AND LEFT(UPPER(TRIM(LEFT_BRAND)), 3) = LEFT(UPPER(TRIM(RIGHT_BRAND)), 3))
                THEN 'T2'
            WHEN (LENGTH(TRIM(LEFT_PRODUCT_NAME)) >= 3 AND LENGTH(TRIM(RIGHT_PRODUCT_NAME)) >= 3
                AND LEFT(UPPER(TRIM(LEFT_PRODUCT_NAME)), 3) = LEFT(UPPER(TRIM(RIGHT_PRODUCT_NAME)), 3))
                THEN 'T2'
            ELSE 'T3'
        END AS MATCH_TYPE
    FROM BLOCKED_PAIRS
)
SELECT
    ROW_NUMBER() OVER (ORDER BY S.LEFT_SOURCE_SYSTEM, S.LEFT_SOURCE_RECORD_ID, S.RIGHT_SOURCE_SYSTEM, S.RIGHT_SOURCE_RECORD_ID) AS RELATIONSHIP_ID,
    S.LEFT_SOURCE_SYSTEM,
    S.LEFT_SOURCE_RECORD_ID,
    S.RIGHT_SOURCE_SYSTEM,
    S.RIGHT_SOURCE_RECORD_ID,
    S.MATCH_TYPE,
    CASE S.MATCH_TYPE
        WHEN 'T0' THEN 100
        WHEN 'T1' THEN 85
        WHEN 'T2' THEN 70
    END AS MATCH_SCORE,
    CASE S.MATCH_TYPE
        WHEN 'T0' THEN 'HIGH'
        WHEN 'T1' THEN 'MEDIUM'
        WHEN 'T2' THEN 'LOW'
    END AS MATCH_CONFIDENCE,
    ROUND((COALESCE(DQL.RECORD_DQ_SCORE, 0) + COALESCE(DQR.RECORD_DQ_SCORE, 0)) / 2, 2) AS DQ_WEIGHTED_SCORE,
    CURRENT_TIMESTAMP() AS CREATED_DTTM
FROM SCORED S
LEFT JOIN RELATIONSHIP_DISCOVERY_DB.INTM.DQ_RECORD_SUMMARY DQL
    ON S.LEFT_SOURCE_SYSTEM = DQL.SOURCE_SYSTEM
    AND S.LEFT_SOURCE_RECORD_ID = DQL.SOURCE_RECORD_ID
LEFT JOIN RELATIONSHIP_DISCOVERY_DB.INTM.DQ_RECORD_SUMMARY DQR
    ON S.RIGHT_SOURCE_SYSTEM = DQR.SOURCE_SYSTEM
    AND S.RIGHT_SOURCE_RECORD_ID = DQR.SOURCE_RECORD_ID
WHERE S.MATCH_TYPE != 'T3';
