CREATE OR REPLACE TABLE RELATIONSHIP_DISCOVERY_DB.INTM.RELATIONSHIP_CATALOG AS
WITH RANKED AS (
    SELECT
        LEFT_SOURCE_SYSTEM,
        LEFT_SOURCE_RECORD_ID,
        RIGHT_SOURCE_SYSTEM,
        RIGHT_SOURCE_RECORD_ID,
        MATCH_TYPE,
        MATCH_SCORE,
        MATCH_CONFIDENCE,
        DQ_WEIGHTED_SCORE,
        CASE MATCH_TYPE
            WHEN 'T0' THEN 1
            WHEN 'T1' THEN 2
            WHEN 'T2' THEN 3
        END AS MATCH_PRIORITY,
        ROW_NUMBER() OVER (
            PARTITION BY LEFT_SOURCE_SYSTEM, LEFT_SOURCE_RECORD_ID
            ORDER BY
                CASE MATCH_TYPE WHEN 'T0' THEN 1 WHEN 'T1' THEN 2 WHEN 'T2' THEN 3 END ASC,
                DQ_WEIGHTED_SCORE DESC,
                MATCH_SCORE DESC,
                RIGHT_SOURCE_SYSTEM ASC,
                RIGHT_SOURCE_RECORD_ID ASC
        ) AS RN
    FROM RELATIONSHIP_DISCOVERY_DB.INTM.RELATIONSHIP_CANDIDATES
)
SELECT
    ROW_NUMBER() OVER (ORDER BY LEFT_SOURCE_SYSTEM, LEFT_SOURCE_RECORD_ID, RIGHT_SOURCE_SYSTEM, RIGHT_SOURCE_RECORD_ID) AS CATALOG_RELATIONSHIP_ID,
    LEFT_SOURCE_SYSTEM,
    LEFT_SOURCE_RECORD_ID,
    RIGHT_SOURCE_SYSTEM,
    RIGHT_SOURCE_RECORD_ID,
    MATCH_TYPE,
    MATCH_SCORE,
    MATCH_CONFIDENCE,
    DQ_WEIGHTED_SCORE,
    MATCH_PRIORITY,
    'Y' AS IS_BEST_MATCH,
    CURRENT_TIMESTAMP() AS CREATED_DTTM
FROM RANKED
WHERE RN = 1;
