CREATE OR REPLACE TABLE RELATIONSHIP_DISCOVERY_DB.INTM.ENTITY_RESOLUTION AS
WITH SOURCE_NORMALIZED AS (
    SELECT
        SS.SOURCE_SYSTEM,
        SS.SOURCE_RECORD_ID,
        SS.BRAND,
        SS.PRODUCT_NAME,
        SS.CATEGORY,
        SS.MANUFACTURER,
        SS.SALE_PRICE,
        SS.SIZE,
        UPPER(TRIM(SS.BRAND)) AS NORMALIZED_BRAND,
        UPPER(TRIM(SS.PRODUCT_NAME)) AS NORMALIZED_PRODUCT_NAME,
        UPPER(TRIM(SS.SIZE)) AS NORMALIZED_SIZE,
        DQ.RECORD_DQ_SCORE
    FROM RELATIONSHIP_DISCOVERY_DB.INTM.SOURCE_SUPERSET SS
    LEFT JOIN RELATIONSHIP_DISCOVERY_DB.INTM.DQ_RECORD_SUMMARY DQ
        ON DQ.SOURCE_SYSTEM = SS.SOURCE_SYSTEM AND DQ.SOURCE_RECORD_ID = SS.SOURCE_RECORD_ID
),
ENTITY_MAP AS (
    SELECT DISTINCT
        NORMALIZED_BRAND,
        NORMALIZED_PRODUCT_NAME,
        NORMALIZED_SIZE,
        DENSE_RANK() OVER (ORDER BY NORMALIZED_BRAND, NORMALIZED_PRODUCT_NAME, NORMALIZED_SIZE) AS ENTITY_SEQ
    FROM SOURCE_NORMALIZED
)
SELECT
    'PRODUCT_' || LPAD(EM.ENTITY_SEQ::VARCHAR, 9, '0') AS ENTITY_KEY,
    SN.NORMALIZED_BRAND,
    SN.NORMALIZED_PRODUCT_NAME,
    SN.NORMALIZED_SIZE,
    SN.SOURCE_SYSTEM,
    SN.SOURCE_RECORD_ID,
    SN.BRAND,
    SN.PRODUCT_NAME,
    SN.CATEGORY,
    SN.MANUFACTURER,
    SN.SALE_PRICE,
    SN.SIZE,
    SN.RECORD_DQ_SCORE,
    CURRENT_TIMESTAMP() AS CREATED_DTTM
FROM SOURCE_NORMALIZED SN
JOIN ENTITY_MAP EM
    ON SN.NORMALIZED_BRAND = EM.NORMALIZED_BRAND
    AND SN.NORMALIZED_PRODUCT_NAME = EM.NORMALIZED_PRODUCT_NAME
    AND SN.NORMALIZED_SIZE = EM.NORMALIZED_SIZE;
