

--Run SQL:RELATIONSHIP CATALOG

SELECT
MATCH_TYPE,
MATCH_CONFIDENCE,
COUNT(*)
FROM RELATIONSHIP_DISCOVERY_DB.INTM.RELATIONSHIP_CATALOG
GROUP BY 1,2
ORDER BY 1,2;


--Run SQL:ACTION LOG

SELECT
ACTION_TYPE,
ACTION_SOURCE,
ACTION_STATUS,
COUNT(*) CNT
FROM RELATIONSHIP_DISCOVERY_DB.LOG.ACTION_LOG
GROUP BY 1,2,3
ORDER BY 1,2;

--Run SQL:HISTORY TABLE

SELECT
ENTITY_KEY,
VERSION_NO,
ACTION_SOURCE,
ACTIVE_FLAG
FROM RELATIONSHIP_DISCOVERY_DB.INTM.INTM_PRODUCT_MASTER
WHERE ENTITY_KEY = '<ENTITY_KEY>'
ORDER BY VERSION_NO;


--Run SQL:UNMASKED ROLE

USE ROLE MDM_ADMIN;

SELECT
SALE_PRICE,
ACTION_SOURCE
FROM RELATIONSHIP_DISCOVERY_DB.FINAL.PRODUCT_MASTER
LIMIT 5;



--Run SQL:MASKED ROLE

USE ROLE MDM_BUSINESS_USER;

SELECT
SALE_PRICE,
ACTION_SOURCE
FROM RELATIONSHIP_DISCOVERY_DB.FINAL.PRODUCT_MASTER
LIMIT 5;


SELECT CURRENT_ROLE();

SELECT
MATCH_TYPE,
MATCH_CONFIDENCE,
COUNT(*)
FROM RELATIONSHIP_DISCOVERY_DB.INTM.RELATIONSHIP_CATALOG
GROUP BY 1,2
ORDER BY 1,2;

SELECT
ACTION_TYPE,
ACTION_SOURCE,
ACTION_STATUS,
COUNT(*) CNT
FROM RELATIONSHIP_DISCOVERY_DB.LOG.ACTION_LOG
GROUP BY 1,2,3
ORDER BY 1,2;

SELECT
ENTITY_KEY,
VERSION_NO,
ACTION_SOURCE,
ACTIVE_FLAG
FROM RELATIONSHIP_DISCOVERY_DB.INTM.INTM_PRODUCT_MASTER
WHERE ENTITY_KEY = '<ENTITY_KEY>'
ORDER BY VERSION_NO;

USE ROLE MDM_ADMIN;

SELECT
SALE_PRICE,
ACTION_SOURCE
FROM RELATIONSHIP_DISCOVERY_DB.FINAL.PRODUCT_MASTER
LIMIT 5;

USE ROLE MDM_BUSINESS_USER;

SELECT
SALE_PRICE,
ACTION_SOURCE
FROM RELATIONSHIP_DISCOVERY_DB.FINAL.PRODUCT_MASTER
LIMIT 5;
